title: Flora
email: aviettran@gmail.com
description: >-
  A proof-of-concept Jekyll website for botanical keys.
baseurl: "/jekyll-test"
url: ""
github_username: aviettran

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dirt
author_profile: false
search: true
atom_feed:
  hide: true

sass:
  sass_dir: _sass

page_gen-dirs: true
page_gen:
  - data: species
    template: species
    title_expr: record['genus'] + " " + record['species']
    name: species
    dir_expr: record['genus'].downcase
  - data: genera
    template: genus
    title: genus
    name: genus
    dir: /

permalink: pretty
