title: Flora
email: aviettran@gmail.com
description: >-
  A proof-of-concept Jekyll website for botanical keys.
baseurl: "/jekyll-test"
url: ""
github_username: aviettran

# Build settings
theme: minima

collections:
  genera:
    output: true
  species:
    output: true
